#!/usr/bin/env python3
"""Generate the contained Codex 0.160 compatibility package; never author copies."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def encoded(value: dict) -> bytes:
    return (json.dumps(value, indent=2) + "\n").encode()


def projection(source: Path) -> dict[str, bytes]:
    manifest = json.loads((source / "plugin.json").read_bytes())
    extension = manifest["extensions"]["com.openai"]
    legacy = {"name": manifest["name"], "version": manifest["version"],
              "description": manifest["description"], "author": manifest["author"],
              "homepage": manifest["homepage"], "repository": manifest["repository"],
              "license": manifest["license"], "keywords": manifest["keywords"],
              "skills": "./skills", "mcpServers": "./.mcp.json", "hooks": extension["hooks"],
              "interface": extension["interface"],
              "extensions": {"com.openai": {"onboardingSkill": extension["onboardingSkill"]}}}
    portable_mcp = json.loads((source / "mcp.json").read_bytes())
    mcp = {"mcpServers": {name: {**{key: value for key, value in server.items() if key not in {"type", "args"}},
                                        "args": [arg.replace("${PLUGIN_ROOT}/", "./") for arg in server.get("args", [])],
                                        "cwd": ".", "env_vars": ["CODEX_HOME"]}
                          for name, server in portable_mcp["mcpServers"].items()}}
    files = {".codex-plugin/plugin.json": encoded(legacy), ".mcp.json": encoded(mcp)}
    for directory in ("skills", "com.openai/agents", "com.openai/hooks", "com.openai/codex_agents", "licenses"):
        for path in sorted((source / directory).rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts:
                if path.is_symlink():
                    raise ValueError("Generated packages require regular source files.")
                files[str(path.relative_to(source))] = path.read_bytes()
    for name in ("skills-lock.json", "THIRD_PARTY_NOTICES.md", "README.md"):
        files[name] = (source / name).read_bytes()
    files["GENERATED.md"] = (
        "Generated by scripts/build_codex_package.py from plugins/product-development.\n"
        "Do not edit this install package. Codex 0.160 skips portable-package hooks;\n"
        "this contained compatibility layout preserves native hook discovery.\n"
        "Regenerate and check this projection whenever its authored source changes.\n"
    ).encode()
    return files


def check(source: Path, destination: Path) -> bool:
    actual = {str(path.relative_to(destination)): path.read_bytes()
              for path in destination.rglob("*")
              if path.is_file() and "__pycache__" not in path.parts}
    return actual == projection(source) and not any(path.is_symlink() for path in destination.rglob("*"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = Path(__file__).resolve().parents[1] / "plugins/product-development"
    destination = source / "com.openai/codex-package"
    if args.check:
        valid = check(source, destination)
        print("Codex install package matches its authored source." if valid else "Regenerate the Codex install package.")
        return int(not valid)
    desired = projection(source)
    for path in destination.rglob("*") if destination.exists() else []:
        if path.is_symlink():
            raise ValueError("Refusing symlinked generated output.")
        if path.is_file() and "__pycache__" not in path.parts and str(path.relative_to(destination)) not in desired:
            raise ValueError("Unexpected generated file; inspect before removing it.")
    for name, data in desired.items():
        path = destination / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
