#!/usr/bin/env python3
"""Generate Codex runtime copies and 0.160 packages from their authored sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]
RUNTIME = REPOSITORY / "adapters/codex_agents"


def encoded(value: dict) -> bytes:
    return (json.dumps(value, indent=2) + "\n").encode()


def runtime_projection() -> dict[str, bytes]:
    return {name: (RUNTIME / name).read_bytes() for name in ("manager.py", "server.py", "hook.py")}


def runtime_matches(source: Path) -> bool:
    directory = source / "com.openai/codex_agents"
    expected = runtime_projection()
    actual = {path.name: path.read_bytes() for path in directory.glob("*.py")}
    return actual == expected and not any(path.is_symlink() for path in directory.rglob("*"))


def projection(source: Path) -> dict[str, bytes]:
    manifest = json.loads((source / "plugin.json").read_bytes())
    extension = manifest["extensions"]["com.openai"]
    legacy = {key: manifest[key] for key in (
        "name", "version", "description", "author", "homepage", "repository", "license", "keywords")}
    legacy.update(skills="./skills", mcpServers="./.mcp.json", hooks=extension["hooks"],
                  interface=extension["interface"], extensions={
                      "com.openai": {"onboardingSkill": extension["onboardingSkill"]}})
    portable_mcp = json.loads((source / "mcp.json").read_bytes())
    mcp = {"mcpServers": {name: {
        **{key: value for key, value in server.items() if key not in {"type", "args"}},
        "args": [arg.replace("${PLUGIN_ROOT}/", "./") for arg in server.get("args", [])],
        "cwd": ".", "env_vars": ["CODEX_HOME"],
    } for name, server in portable_mcp["mcpServers"].items()}}
    files = {".codex-plugin/plugin.json": encoded(legacy), ".mcp.json": encoded(mcp)}
    for directory in ("skills", "com.openai", "assets", "licenses"):
        for path in sorted((source / directory).rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts and not path.is_relative_to(source / "com.openai/codex-package"):
                if path.is_symlink():
                    raise ValueError("Generated packages require regular source files.")
                files[str(path.relative_to(source))] = path.read_bytes()
    files.update({"com.openai/codex_agents/" + name: data for name, data in runtime_projection().items()})
    for name in ("skills-lock.json", "THIRD_PARTY_NOTICES.md", "README.md"):
        if (source / name).exists():
            files[name] = (source / name).read_bytes()
    files["GENERATED.md"] = (
        f"Generated by scripts/build_codex_package.py from plugins/{manifest['name']}.\n"
        "Do not edit this install package or its generated runtime copies.\n"
        "Codex 0.160 skips portable-package hooks; this contained compatibility\n"
        "layout preserves native discovery. adapters/codex_agents owns the\n"
        "installer code; each plugin owns its catalog, instructions and state.\n"
    ).encode()
    return files


def check(source: Path, destination: Path) -> bool:
    actual = {str(path.relative_to(destination)): path.read_bytes()
              for path in destination.rglob("*")
              if path.is_file() and "__pycache__" not in path.parts}
    return (runtime_matches(source) and actual == projection(source)
            and not any(path.is_symlink() for path in destination.rglob("*")))


def write_generated(destination: Path, desired: dict[str, bytes]) -> None:
    for path in destination.rglob("*") if destination.exists() else []:
        if path.is_symlink():
            raise ValueError("Refusing symlinked generated output.")
        if path.is_file() and "__pycache__" not in path.parts and str(path.relative_to(destination)) not in desired:
            raise ValueError("Unexpected generated file; inspect before removing it.")
    for name, data in desired.items():
        path = destination / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--plugin", help="One plugin directory name; default checks all owned catalogs.")
    args = parser.parse_args()
    sources = [REPOSITORY / "plugins" / args.plugin] if args.plugin else sorted(
        path.parents[2] for path in (REPOSITORY / "plugins").glob("*/com.openai/agents/catalog.json"))
    valid = True
    for source in sources:
        destination = source / "com.openai/codex-package"
        if args.check:
            current = check(source, destination)
            print(f"{source.name}: {'matches authored source' if current else 'regenerate the install package'}.")
            valid = current and valid
        else:
            write_generated(source / "com.openai/codex_agents", runtime_projection())
            write_generated(destination, projection(source))
    return int(not valid)


if __name__ == "__main__":
    raise SystemExit(main())
